name: Check URLs from changed files

on:
  push:
  pull_request:

jobs:
  job:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Get changed files
        id: file-changes
        uses: trilom/file-changes-action@v1.2.4
        with:
          output: ''

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - run: |
          gem install awesome_bot

      - name: Check each changed file
        run: |
          for file in ${{ steps.file-changes.outputs.files_modified }}; do
            echo;
            echo "::group::Processing file... $file"
            awesome_bot "$file" --allow-redirect --allow-dupe --allow-ssl || true;
            echo "::endgroup::"
          done

      - uses: actions/upload-artifact@v3
        with:
          path: ${{ github.workspace }}/*.json
